DISEASE_INFO = {
    "Apple__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Malus domestica (Healthy)",
        "description": "The apple fruit appears completely healthy with no visible signs of fungal, bacterial, or viral infection. The skin texture, color, and firmness are all within normal parameters indicating optimal growing conditions and proper post-harvest handling.",
        "treatment": "No treatment required. Continue regular monitoring and maintain good agricultural practices.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Maintain good air circulation around trees. Regular pruning to remove dead branches. Apply preventive fungicide spray during flowering season. Store harvested fruits in cool dry conditions at 0-4°C.",
        "farmer_tips": "Keep monitoring weekly. Ensure proper irrigation and avoid waterlogging. Use balanced NPK fertilizer for best fruit quality.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Apple__Rotten": {
        "status": "Diseased",
        "disease_name": "Apple Fruit Rot",
        "scientific_name": "Botrytis cinerea / Monilinia fructigena",
        "description": "The apple shows advanced signs of fungal rot disease. Brown soft spots are visible on the fruit surface indicating tissue breakdown. The disease is caused by Botrytis cinerea or Monilinia fructigena fungi that penetrate through wounds or natural openings. Disease spreads rapidly in warm humid conditions above 20°C.",
        "treatment": "1. Remove and destroy all infected fruits immediately.\n2. Apply Mancozeb fungicide (2g/litre water) spray.\n3. Use Captan 50WP fungicide as preventive treatment.\n4. Improve cold storage conditions (0-2°C, 90% humidity).\n5. Apply post-harvest fungicide dip treatment.",
        "severity": "High",
        "severity_score": 8,
        "prevention": "Avoid physical injury during harvest. Use clean sanitized containers. Apply pre-harvest calcium sprays to strengthen cell walls. Maintain cold chain storage. Remove fallen fruits from orchard floor regularly.",
        "farmer_tips": "Inspect entire harvest batch immediately. Separate healthy fruits from diseased ones. Ensure cold storage temperature is maintained. Contact agricultural officer if outbreak is large scale.",
        "affected_parts": "Fruit skin, pulp, core",
        "spread_risk": "High — spreads through contact and air",
        "economic_impact": "Can cause 30-50% crop loss if untreated."
    },
    "Banana__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Musa acuminata (Healthy)",
        "description": "The banana appears completely healthy with uniform yellow color, firm texture and no signs of disease or pest damage. Optimal ripening stage with no fungal or bacterial infection visible.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Maintain proper temperature 13-14°C during storage. Avoid mechanical damage during harvest and transport. Ensure good ventilation in storage.",
        "farmer_tips": "Harvest at correct maturity stage. Handle with care to prevent bruising. Store away from ethylene producing fruits.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Banana__Rotten": {
        "status": "Diseased",
        "disease_name": "Banana Crown Rot / Anthracnose",
        "scientific_name": "Colletotrichum musae / Fusarium pallidoroseum",
        "description": "The banana shows signs of crown rot or anthracnose disease caused by Colletotrichum musae fungus. Dark brown to black discoloration visible on the skin with soft mushy texture indicating internal tissue breakdown. Disease spreads rapidly at temperatures above 25°C with high humidity.",
        "treatment": "1. Remove and destroy infected bananas immediately.\n2. Apply Thiabendazole fungicide dip (500ppm) post-harvest.\n3. Use Prochloraz fungicide spray on crown area.\n4. Maintain cold storage at 13-14°C.\n5. Apply hot water treatment (50°C for 3 minutes) before storage.",
        "severity": "High",
        "severity_score": 8,
        "prevention": "Use clean sanitized cutting tools during harvest. Apply fungicide dip immediately after harvest. Maintain cold chain storage. Ensure good ventilation to reduce humidity.",
        "farmer_tips": "Check entire batch if one banana shows symptoms. Separate infected bananas immediately. Consult local agricultural extension officer for outbreak management.",
        "affected_parts": "Skin, pulp, crown area",
        "spread_risk": "Very High — spreads rapidly through contact",
        "economic_impact": "Can cause 20-40% post-harvest loss."
    },
    "Mango__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Mangifera indica (Healthy)",
        "description": "The mango appears completely healthy with good skin color, firm texture and no signs of disease. No visible spots, lesions, or discoloration indicating proper growing and storage conditions.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Regular orchard hygiene. Proper pruning for air circulation. Pre-harvest copper fungicide spray. Careful harvesting to avoid wounds.",
        "farmer_tips": "Harvest at correct maturity. Store at 8-12°C for longer shelf life. Avoid exposing to direct sunlight after harvest.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Mango__Rotten": {
        "status": "Diseased",
        "disease_name": "Mango Anthracnose / Stem End Rot",
        "scientific_name": "Colletotrichum gloeosporioides / Lasiodiplodia theobromae",
        "description": "The mango shows severe anthracnose or stem end rot disease. Dark black irregular spots visible on skin surface with soft decayed areas. Colletotrichum gloeosporioides is the primary pathogen causing pre and post-harvest losses. Disease can remain latent until fruit ripening then develop rapidly within 2-3 days.",
        "treatment": "1. Apply Copper Oxychloride (3g/litre) spray 15 days before harvest.\n2. Hot water treatment (52°C for 5 minutes) immediately after harvest.\n3. Apply Carbendazim fungicide (1g/litre) post-harvest dip.\n4. Store at 8-12°C with 85-90% relative humidity.\n5. Remove and destroy all infected fruits.",
        "severity": "High",
        "severity_score": 9,
        "prevention": "Apply preventive copper fungicide sprays during flowering. Avoid wounding during harvest. Maintain orchard hygiene by removing fallen fruits. Use disease free planting material.",
        "farmer_tips": "Spray fungicide 2-3 weeks before harvest as preventive measure. Sort and grade fruits carefully after harvest. Ensure cold storage is maintained throughout supply chain.",
        "affected_parts": "Skin, pulp, seed area, stem end",
        "spread_risk": "High — spreads through rain splash and contact",
        "economic_impact": "Major export losses. Can cause 40-60% post-harvest loss."
    },
    "Orange__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Citrus sinensis (Healthy)",
        "description": "The orange appears completely healthy with bright uniform color, firm skin and no signs of fungal or bacterial disease. Optimal citrus fruit condition with no visible pathogen infection.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Regular copper fungicide spray in orchard. Proper irrigation management. Good drainage to prevent waterlogging.",
        "farmer_tips": "Store at 3-9°C with 85-90% humidity. Avoid mechanical damage during transport. Regular inspection during storage.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Orange__Rotten": {
        "status": "Diseased",
        "disease_name": "Citrus Green Mold / Blue Mold",
        "scientific_name": "Penicillium digitatum / Penicillium italicum",
        "description": "The orange shows signs of green or blue mold caused by Penicillium fungus. Soft water-soaked spots visible on skin with white mycelium growth turning green or blue-green. This is the most economically important post-harvest disease of citrus affecting 80% of citrus losses worldwide. Disease spreads rapidly through wounds and natural openings.",
        "treatment": "1. Apply Imazalil fungicide (500-1000ppm) post-harvest dip.\n2. Use Thiabendazole (1000ppm) as alternative fungicide.\n3. Apply Sodium bicarbonate solution (2-3%) as organic alternative.\n4. Maintain cold storage at 3-5°C.\n5. Use UV-C light treatment for surface sterilization.",
        "severity": "High",
        "severity_score": 8,
        "prevention": "Handle oranges carefully to prevent wounds. Sanitize packing equipment regularly. Apply wax coating after harvest. Maintain cold chain storage throughout distribution.",
        "farmer_tips": "Sort infected fruits immediately after detection. Apply fungicide treatment within 24 hours of harvest. Maintain proper cold storage temperature consistently.",
        "affected_parts": "Skin, peel, pulp segments",
        "spread_risk": "Very High — spreads through air spores",
        "economic_impact": "Responsible for 80% of citrus post-harvest losses worldwide."
    },
    "Grape__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Vitis vinifera (Healthy)",
        "description": "The grape bunch appears completely healthy with uniform color, firm berries and no signs of fungal or bacterial disease. Good grape condition suitable for fresh consumption or wine production.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Regular pruning for air circulation. Preventive fungicide spray during growing season. Proper canopy management.",
        "farmer_tips": "Harvest at correct sugar level (Brix). Handle gently to avoid bruising. Store at 0-2°C with SO2 generator pads.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Grape__Rotten": {
        "status": "Diseased",
        "disease_name": "Botrytis Bunch Rot / Grey Mold",
        "scientific_name": "Botrytis cinerea",
        "description": "The grape shows severe Botrytis bunch rot also known as grey mold. Brown water-soaked lesions visible on berries with characteristic grey fuzzy fungal growth. Botrytis cinerea is the most destructive grape disease worldwide. Disease spreads rapidly in cool humid conditions (15-20°C, >90% humidity) and can destroy entire grape bunches within 48 hours.",
        "treatment": "1. Apply Fenhexamid (Switch) fungicide immediately.\n2. Use Cyprodinil + Fludioxonil combination fungicide.\n3. Remove infected bunches from vineyard immediately.\n4. Improve canopy ventilation by leaf removal.\n5. Apply SO2 pads in storage to prevent spread.",
        "severity": "High",
        "severity_score": 9,
        "prevention": "Maintain good air circulation in vineyard. Avoid overhead irrigation. Apply preventive fungicide at flowering stage. Remove infected material from vineyard floor regularly.",
        "farmer_tips": "Inspect vineyard twice weekly during humid periods. Remove infected bunches immediately before disease spreads. Rotate fungicide classes to prevent resistance development.",
        "affected_parts": "Berries, bunch stems, leaves",
        "spread_risk": "Extremely High — destroys entire bunches rapidly",
        "economic_impact": "Can cause 100% bunch loss in severe infections."
    },
    "Strawberry__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Fragaria ananassa (Healthy)",
        "description": "The strawberry appears completely healthy with bright red uniform color, firm texture and no signs of disease. Good strawberry condition with no visible fungal grey mold or leather rot infection.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Use raised beds for better drainage. Avoid overhead irrigation. Apply mulch to prevent soil splash. Regular removal of old leaves.",
        "farmer_tips": "Harvest every 2-3 days during peak season. Store at 0-2°C immediately after harvest. Handle gently to prevent bruising.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Strawberry__Rotten": {
        "status": "Diseased",
        "disease_name": "Strawberry Grey Mold / Leather Rot",
        "scientific_name": "Botrytis cinerea / Phytophthora cactorum",
        "description": "The strawberry shows signs of grey mold caused by Botrytis cinerea or leather rot caused by Phytophthora cactorum. Brown water-soaked lesions visible with grey fuzzy growth on infected areas. Disease spreads rapidly in cool moist conditions and can destroy entire strawberry patches within days.",
        "treatment": "1. Apply Iprodione or Fenhexamid fungicide spray.\n2. Remove infected fruits immediately from field.\n3. Improve air circulation around plants.\n4. Reduce irrigation frequency.\n5. Apply copper hydroxide as preventive treatment.",
        "severity": "High",
        "severity_score": 8,
        "prevention": "Use drip irrigation instead of overhead. Plant on raised beds. Ensure proper plant spacing for air circulation. Remove old infected plant material regularly.",
        "farmer_tips": "Harvest frequently during disease-prone weather. Remove infected fruits before they spread. Avoid harvesting during wet conditions.",
        "affected_parts": "Fruit, calyx, crown",
        "spread_risk": "High — spreads through water splash and contact",
        "economic_impact": "Can cause 50-80% loss during wet seasons."
    },
    "Tomato__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Solanum lycopersicum (Healthy)",
        "description": "The tomato appears completely healthy with uniform red color, firm texture and no signs of bacterial or fungal disease. Good tomato condition suitable for fresh consumption or processing.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Regular inspection. Proper staking and pruning. Balanced fertilization. Good drainage management.",
        "farmer_tips": "Harvest at correct ripeness stage. Store at 10-15°C for longer shelf life. Avoid refrigerating unripe tomatoes.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Tomato__Rotten": {
        "status": "Diseased",
        "disease_name": "Tomato Blossom End Rot / Bacterial Soft Rot",
        "scientific_name": "Calcium deficiency / Pectobacterium carotovorum",
        "description": "The tomato shows signs of blossom end rot or bacterial soft rot. Dark sunken lesion visible at blossom end with soft mushy texture throughout the fruit. Blossom end rot is caused by calcium deficiency combined with irregular watering. Bacterial soft rot is caused by Pectobacterium bacteria entering through wounds.",
        "treatment": "1. Apply calcium nitrate foliar spray (0.5-1%) immediately.\n2. Maintain consistent irrigation schedule.\n3. Apply lime to soil to improve calcium availability.\n4. Remove and destroy infected fruits.\n5. Apply copper bactericide spray for bacterial soft rot.",
        "severity": "High",
        "severity_score": 7,
        "prevention": "Maintain consistent soil moisture. Apply mulch to retain moisture. Regular calcium foliar sprays. Avoid over-fertilization with nitrogen. Ensure good soil drainage.",
        "farmer_tips": "Check soil calcium and pH levels. Install drip irrigation for consistent watering. Apply calcium spray at first fruit set stage as prevention.",
        "affected_parts": "Blossom end, fruit pulp",
        "spread_risk": "Medium — bacterial form spreads through water",
        "economic_impact": "Can affect 10-30% of tomato crop."
    },
    "Potato__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Solanum tuberosum (Healthy)",
        "description": "The potato appears completely healthy with firm texture, clean skin and no signs of late blight or soft rot disease. Good potato condition suitable for storage and consumption.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Store in cool dark place at 4-10°C. Ensure good ventilation in storage. Regular inspection during storage period.",
        "farmer_tips": "Cure harvested potatoes at 15-20°C for 2 weeks before storage. Remove damaged potatoes before storage. Keep away from light to prevent greening.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Potato__Rotten": {
        "status": "Diseased",
        "disease_name": "Potato Late Blight / Soft Rot",
        "scientific_name": "Phytophthora infestans / Pectobacterium atrosepticum",
        "description": "The potato shows severe signs of late blight caused by Phytophthora infestans or bacterial soft rot. Dark brown to black lesions visible on skin with internal browning and foul smell. Late blight caused the Irish Potato Famine of 1845 destroying entire potato crops. Disease spreads extremely rapidly in cool wet conditions.",
        "treatment": "1. Apply Metalaxyl + Mancozeb fungicide immediately.\n2. Remove and destroy all infected potatoes.\n3. Improve storage ventilation and reduce humidity.\n4. Apply copper-based fungicide as preventive measure.\n5. Store healthy potatoes at 4°C with good airflow.",
        "severity": "High",
        "severity_score": 9,
        "prevention": "Use certified disease-free seed potatoes. Apply preventive fungicide before disease appears. Ensure good drainage in field. Avoid overhead irrigation. Remove infected plant debris.",
        "farmer_tips": "Inspect stored potatoes weekly. Remove any infected potato immediately to prevent spread. Ensure storage temperature and humidity are correct. Use resistant varieties in disease-prone areas.",
        "affected_parts": "Skin, tuber flesh, eyes",
        "spread_risk": "Extremely High — spreads through air and water",
        "economic_impact": "Historically caused famines. Can destroy 100% of crop."
    },
    "Bellpepper__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Capsicum annuum (Healthy)",
        "description": "The bell pepper appears completely healthy with uniform color, firm texture and no signs of bacterial or fungal disease.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Regular inspection. Proper irrigation management. Avoid wounding during harvest.",
        "farmer_tips": "Harvest at correct color stage. Store at 7-10°C with 90-95% humidity.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Bellpepper__Rotten": {
        "status": "Diseased",
        "disease_name": "Bell Pepper Anthracnose / Soft Rot",
        "scientific_name": "Colletotrichum capsici / Erwinia carotovora",
        "description": "The bell pepper shows signs of anthracnose or bacterial soft rot. Dark sunken circular lesions visible on fruit surface with water-soaked appearance and soft mushy texture. Disease spreads rapidly in warm humid conditions.",
        "treatment": "1. Remove and destroy infected fruits immediately.\n2. Apply Copper Oxychloride fungicide spray.\n3. Use Mancozeb (2g/litre) as preventive spray.\n4. Improve field drainage and air circulation.\n5. Apply bactericide for bacterial soft rot control.",
        "severity": "High",
        "severity_score": 7,
        "prevention": "Avoid wounding during harvest and transport. Use clean sanitized equipment. Maintain proper field drainage. Apply preventive fungicide spray.",
        "farmer_tips": "Handle peppers carefully during harvest. Sort and grade before storage. Maintain cold chain storage throughout distribution.",
        "affected_parts": "Fruit skin, flesh, seed cavity",
        "spread_risk": "High — spreads through rain splash",
        "economic_impact": "Can cause 20-40% post-harvest loss."
    },
    "Guava__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Psidium guajava (Healthy)",
        "description": "The guava appears completely healthy with good skin color, firm texture and no visible disease symptoms.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Regular pruning. Proper orchard sanitation. Preventive copper spray during rainy season.",
        "farmer_tips": "Harvest at correct maturity. Handle carefully to avoid bruising. Store at 8-10°C.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Guava__Rotten": {
        "status": "Diseased",
        "disease_name": "Guava Fruit Rot / Anthracnose",
        "scientific_name": "Colletotrichum gloeosporioides / Phytophthora nicotianae",
        "description": "The guava shows signs of fruit rot or anthracnose disease. Dark brown lesions with soft decayed areas visible on skin surface. Disease progresses rapidly from skin to internal pulp causing complete fruit breakdown.",
        "treatment": "1. Apply Carbendazim (1g/litre) fungicide spray.\n2. Remove and destroy infected fruits.\n3. Apply Copper Oxychloride as preventive spray.\n4. Improve orchard drainage.\n5. Reduce humidity around fruit clusters.",
        "severity": "High",
        "severity_score": 7,
        "prevention": "Regular orchard sanitation. Remove fallen fruits regularly. Apply preventive fungicide before rainy season. Ensure proper spacing for air circulation.",
        "farmer_tips": "Harvest before full ripeness for longer shelf life. Apply wax coating after harvest. Store in well ventilated cool area.",
        "affected_parts": "Skin, pulp, seed cavity",
        "spread_risk": "High — spreads through rain and insects",
        "economic_impact": "Can cause 30-50% post-harvest loss."
    },
    "Pomegranate__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Punica granatum (Healthy)",
        "description": "The pomegranate appears completely healthy with good skin color, firm texture and no signs of bacterial blight or heart rot disease.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Regular inspection. Proper orchard sanitation. Preventive copper spray during flowering.",
        "farmer_tips": "Harvest at correct ripeness. Store at 5-8°C with 80-85% humidity. Handle carefully to avoid cracking.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Pomegranate__Rotten": {
        "status": "Diseased",
        "disease_name": "Pomegranate Heart Rot / Bacterial Blight",
        "scientific_name": "Alternaria alternata / Xanthomonas axonopodis",
        "description": "The pomegranate shows signs of heart rot or bacterial blight. External browning and cracking visible with internal seed and aril discoloration. Disease often develops internally making early detection difficult. Alternaria heart rot causes complete internal rotting while maintaining external appearance.",
        "treatment": "1. Apply Copper Oxychloride (3g/litre) spray before harvest.\n2. Use Carbendazim + Mancozeb combination fungicide.\n3. Apply Streptomycin for bacterial blight control.\n4. Remove and destroy infected fruits.\n5. Improve orchard drainage and air circulation.",
        "severity": "High",
        "severity_score": 8,
        "prevention": "Apply preventive copper spray at fruit development stage. Avoid fruit injuries during harvest. Maintain proper orchard sanitation. Remove mummified fruits from trees.",
        "farmer_tips": "Check fruits by pressing gently — soft spots indicate internal rot. Apply preventive fungicide 3-4 weeks before harvest. Sort carefully before storage.",
        "affected_parts": "Arils, seeds, internal membranes",
        "spread_risk": "Medium — spreads through wounds and rain",
        "economic_impact": "High export loss due to internal damage not visible externally."
    },
    "Carrot__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Daucus carota (Healthy)",
        "description": "The carrot appears completely healthy with uniform orange color, firm texture and no signs of bacterial soft rot or black rot disease.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Store in cool humid conditions at 0-4°C. Ensure good ventilation. Remove foliage tops before storage.",
        "farmer_tips": "Store with high humidity (95-100%) to prevent wilting. Remove damaged carrots before storage. Keep away from ethylene producing fruits.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Carrot__Rotten": {
        "status": "Diseased",
        "disease_name": "Carrot Soft Rot / Black Rot",
        "scientific_name": "Pectobacterium carotovorum / Alternaria radicina",
        "description": "The carrot shows signs of bacterial soft rot or black rot fungal disease. Water-soaked lesions with foul smell visible indicating bacterial infection or dark black lesions at crown indicating Alternaria black rot. Disease spreads rapidly in warm conditions above 20°C.",
        "treatment": "1. Remove and destroy infected carrots immediately.\n2. Improve storage ventilation to reduce humidity.\n3. Lower storage temperature to 0-2°C.\n4. Apply copper-based bactericide for bacterial rot.\n5. Use Iprodione fungicide for Alternaria black rot.",
        "severity": "High",
        "severity_score": 7,
        "prevention": "Avoid physical damage during harvest. Store at correct temperature immediately after harvest. Ensure good drainage in storage facility. Remove infected material promptly.",
        "farmer_tips": "Sort carrots carefully before storage. Remove any damaged or cracked carrots. Maintain storage temperature consistently at 0-4°C.",
        "affected_parts": "Root body, crown, tip",
        "spread_risk": "High — bacterial form spreads rapidly in storage",
        "economic_impact": "Can cause 20-40% storage losses."
    },
    "Cucumber__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Cucumis sativus (Healthy)",
        "description": "The cucumber appears completely healthy with uniform dark green color, firm texture and no signs of pythium rot or angular leaf spot disease.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Store at 10-13°C with 90-95% humidity. Avoid chilling injury below 10°C. Handle carefully to prevent bruising.",
        "farmer_tips": "Harvest at correct size before over-maturity. Wrap individually for longer shelf life. Store away from ethylene producing fruits.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Cucumber__Rotten": {
        "status": "Diseased",
        "disease_name": "Cucumber Pythium Rot / Belly Rot",
        "scientific_name": "Pythium aphanidermatum / Rhizoctonia solani",
        "description": "The cucumber shows signs of Pythium rot or belly rot disease. Water-soaked lesions visible on fruit surface with rapid progression to complete fruit collapse. Pythium aphanidermatum thrives in warm wet soil conditions and spreads through irrigation water and soil contact.",
        "treatment": "1. Apply Metalaxyl fungicide (Ridomil) immediately.\n2. Remove infected fruits from field.\n3. Improve field drainage to reduce waterlogging.\n4. Reduce irrigation frequency.\n5. Apply Copper Oxychloride as preventive treatment.",
        "severity": "High",
        "severity_score": 8,
        "prevention": "Use raised bed cultivation. Apply plastic mulch to prevent soil contact. Drip irrigation instead of flood irrigation. Ensure good field drainage.",
        "farmer_tips": "Check field drainage regularly. Avoid over-irrigation especially during fruiting stage. Remove infected fruits immediately before disease spreads.",
        "affected_parts": "Fruit skin, flesh, entire fruit",
        "spread_risk": "Very High — spreads through irrigation water",
        "economic_impact": "Can cause 40-60% loss in severely affected fields."
    },
    "Jujube__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Ziziphus jujuba (Healthy)",
        "description": "The jujube appears completely healthy with good skin color, firm texture and no visible disease symptoms.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Regular inspection and proper orchard care. Preventive fungicide spray during rainy season.",
        "farmer_tips": "Harvest at correct ripeness stage. Handle carefully to avoid bruising. Store at 0-5°C for longer shelf life.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    },
    "Jujube__Rotten": {
        "status": "Diseased",
        "disease_name": "Jujube Fruit Rot / Black Spot",
        "scientific_name": "Alternaria alternata / Colletotrichum gloeosporioides",
        "description": "The jujube shows signs of fruit rot or black spot disease caused by fungal infection. Dark brown to black lesions visible on skin surface with soft decayed areas indicating internal tissue breakdown.",
        "treatment": "1. Apply Carbendazim fungicide spray.\n2. Remove and destroy infected fruits.\n3. Apply Copper Oxychloride as preventive treatment.\n4. Improve orchard air circulation.\n5. Reduce humidity around fruit clusters.",
        "severity": "High",
        "severity_score": 7,
        "prevention": "Regular orchard sanitation. Remove fallen fruits. Apply preventive fungicide before rainy season. Proper pruning for air circulation.",
        "farmer_tips": "Harvest before full ripeness for longer shelf life. Apply wax coating after harvest. Store in cool well ventilated area.",
        "affected_parts": "Skin, pulp, seed",
        "spread_risk": "High — spreads through rain and wind",
        "economic_impact": "Can cause 20-35% post-harvest loss."
    },
    "Strawberry__Healthy": {
        "status": "Healthy",
        "disease_name": "No Disease Detected",
        "scientific_name": "Fragaria ananassa (Healthy)",
        "description": "The strawberry appears completely healthy with bright red color and firm texture.",
        "treatment": "No treatment required.",
        "severity": "None",
        "severity_score": 0,
        "prevention": "Avoid overhead irrigation. Use raised beds. Regular removal of old leaves.",
        "farmer_tips": "Harvest every 2-3 days. Store at 0-2°C immediately after harvest.",
        "affected_parts": "None",
        "spread_risk": "None",
        "economic_impact": "No economic loss expected."
    }
}
